version: "3.9"

services:
  db:
    image: postgres:13
    container_name: db_container
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      args:
        - workdir=$WORKDIR
    container_name: web_container
    env_file:
      - .env
    depends_on:
      - db

volumes:
    db_data:
