services:
  web:
    build:
      args:
        - config=dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/app/
    ports:
      - "8000:8000"

  db:
    ports:
    - "5432:5432"